name: Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          cd my-app
          docker build -t azure-test-image .

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Tag Docker image as latest and git commit sha
        run: |
         docker tag azure-test-image "${{ secrets.DOCKER_HUB_USERNAME }}/azure:latest"
         docker tag azure-test-image "${{ secrets.DOCKER_HUB_USERNAME }}/azure:${{ github.sha }}"


      - name: Push Docker image
        run: |
          docker push "${{ secrets.DOCKER_HUB_USERNAME }}/azure:latest"
          docker push "${{ secrets.DOCKER_HUB_USERNAME }}/azure:${{ github.sha }}"
      
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az extension add --name bicep
        shell: bash

      - name: Build Bicep Template
        run: |
          az bicep build -f path/to/your/bicep/template.bicep
        working-directory: ${{ github.workspace }}

      - name: Deploy Bicep Template
        run: |
          rgName="<ResourceGroupName>" # Replace with your desired resource group name
          az deployment group create \
            --name myDeployment \
            --resource-group $rgName \
            --template-file ./main.bicep \
            --parameters @parameters.json # If you have parameter files
        working-directory: ${{ github.workspace }}

      

